### PR TITLE
Temporarily disable spaces for Fall 2020

### LINKED ISSUE #1047: Disable interactivity for space finder cards
Here's what we're considering at the moment:

- [ ] reduce opacity while maintaining accessibility
- [x] disable any/all links within cards
- [x] remove reserve buttons

### PR DESCRIPTION
**Pull request by cappadona**
[Deployed to dev](http://mannlib-dev.internal.library.cornell.edu/locomotive/thoughtless-marsh-6015/preview/use/spaces/)

I still need to put opacity reduction through accessibility paces...

> Resolves #1047

### CODE REVIEW

**Comment by eeh53** [comment]
Thanks, @cappadona! Glad you noted that you still need to test the opacity since I noticed that immediately ;)

Love the text in the alert box, and particularly the mention of the behavioral compact. My only note is that there will be quiet study zones on both the 1st and 2nd floors.

**Comment by cappadona** [comment]
Ha...thanks @eeh53. That was my attempt to will our way to the first floor only. The great news is that thanks to #1064, that alert text is fully managed via the back office 😉

**Comment by cappadona** [comment]
[50% opacity for spaces cards](http://mannlib-dev.internal.library.cornell.edu/locomotive/thoughtless-marsh-6015/preview/use/spaces/classrooms) is accessible according to SiteImprove Chome extension and Firefox Dev Accesssibility.

@kevinkidwell – do you mind double checking when you have a moment?

**Comment by kevinkidwell** [comment]
@cappadona SiteImprove (and other automated color contrast checkers) can't take opacity into account when analyzing a site. [This article](https://www.practicalecommerce.com/How-to-Measure-Color-Contrast-for-Web-Accessibility) explains a little more.

I just used a browser color picker extension to grab the color of the text for Stone Classroom, which gave me #868B8E as the color code. Plugging that into the contrast checker, it fails contrast ratio: https://webaim.org/resources/contrastchecker/?fcolor=868B8E&bcolor=FFFFFF. Since that's the darkest element on the cards, I'd guess the others also don't meet 4.5:1.

**Comment by cappadona** [comment]
Great info...thanks @kevinkidwell! I'm on it.

**Comment by cappadona** [comment]
Okay @eeh53. I just [deployed an update of the deactivated space cards to dev](http://mannlib-dev.internal.library.cornell.edu/locomotive/thoughtless-marsh-6015/preview/use/spaces/classrooms), that only targets the card images when reducing opacity.

More details are in the [latest commit](https://github.com/cul-it/mann-wagon/pull/1063/commits/074a0100c9c0bdf4c6869abad4e82eb606d7e351), but essentially if we want to reduce the opacity on the rest of the card, we'll need to drop the location and capacity info or change the color of these two elements. Even then, we wouldn't be able to go beyond 80%.

**Review by sew268 — COMMENTED** [review]
thanks everyone - I'm on board with how this looks now.  Alert text and opacity look great. :)

**Comment by eeh53** [comment]
@cappadona I agree - looks great!

**Review by eeh53 — APPROVED** [review]

**Comment by cappadona** [comment]
@sew268 @eeh53 Deployed to production!

I updated the alert to include the second floor and noted that quiet study reservations are coming soon.

**Pull request merged**
