### PR TITLE
Used webpack plugins to compress js and css assets.

### PR DESCRIPTION
**Pull request by tahirpoduska**
@cappadona Locomotive CMS (engine) should handle asset compression, so not sure if this is PR is needed.

### CODE REVIEW

**Comment by cappadona** [comment]
@tap87 That was my initial thought as well. I should be able to review in the early afternoon and get back to you. Sorry for the delay.

**Review by cappadona — COMMENTED** [review]
Finally had a chance to dig into this. Sorry for the long delay.

I tested this change deploying the content from production as of 3/28/17 in the following 3 environments:
1. wagon
1. local engine
1. dev engine

I recorded significant improvements across the board, more so in the reduction of `DOMContentLoaded` vs overall page load. This makes sense since what's being addressed here are the render blocking assets, while the images are still large and many...

I have added the results to #838.

Three areas which I think can use further review are:
- [ ] `uglifyjs-webpack-plugin@0.3.1` has a peer dependency of `uglify-js@^2.8.0` but we haven't added it to package.json
- [ ] when running `npm start` there is a ton of output from UglifyJS (primarily warnings) -- we should take a closer look at these and see if any need to be addressed
- [ ] Webpack reports main.css minified to `211KB` but when served to the browser, Chrome reports a filesize of `558KB`

Overall, this is a great start...thanks! I'll be submitting a couple PRs today that implement lazy loading for the two carousels on the home page. I'll also push optimized staff and spotlight images.

**Comment by cappadona** [comment]
I almost forgot...I also ran numbers for this PR vs. having Locomotive (via Steam) minify and compress JS & CSS -- a new feature [introduced with Engine `v3.3`](https://locomotive-v3.readme.io/v3.3/docs/version-33#section-features-improvements) I'm including those here.

Again, aside from the anomaly with `main.css` mentioned above, with the limited data in hand there doesn't appear to be much of a benefit in using Locomotive's minifying instead of having Webpack handle it.

One thing worth noting is that since Locomotive doesn't minify while hosting via wagon, it doesn't slow down or affect the development workflow until you go to deploy assets to an engine (which takes significantly longer now). On the other hand, the Webpack plugins are quicker to minify but will run more frequently during the development process. Initial start time for `npm start` was increased but since Webpack is watching files for changes, I don't suspect the inclusion of minifying assets to reduce the developer experience to an extent it will become bothersome. Also, I'm sure we could configure webpack to only minify when prepping assets for production, although that would introduce changes to the existing workflow as well...okay, talk amongst yourselves.

200w_d

### Performance of Engine `v3.3` vs. Baseline
> Percentage of decrease from [baseline data](https://github.com/cul-it/mann-wagon/issues/831) in bold

| Environment | `DOMContentLoaded` | Load |
| --- | --- | --- |
| local engine `v3.3.0.rc2` | 28.17s (**51.4%**) | 54.86s (**6.1%**) |

### Performance of Engine `v3.3` vs. PR #839 
> Percentage of difference from [PR #839 data](https://github.com/cul-it/mann-wagon/issues/838#issuecomment-290712601) in bold

| Environment | `DOMContentLoaded` | Load |
| --- | --- | --- |
| local engine `v3.3.0.rc2` | 28.17s (**3.4% INCREASE**) | 54.86s (**3.1% DECREASE**) |

> Only run against local engine since Locomotive [doesn't minify assets when serving via wagon](https://github.com/locomotivecms/wagon/commit/f3f75d7) and there was no significant difference between baseline numbers in local vs dev engines.

### Performance of Engine `v3.3` combined with PR #839 vs. PR #839 only
> Percentage of difference from [PR #839 data](https://github.com/cul-it/mann-wagon/issues/838#issuecomment-290712601) in bold

| Environment | `DOMContentLoaded` | Load |
| --- | --- | --- |
| wagon `v2.3.0rc1` | 24.76s (**0.09% DECREASE**) | 43.92s (**0.24% INCREASE**) |
| local engine `v3.3.0.rc2` | 29.02s (**6.5% INCREASE**) | 55.51s (**2% DECREASE**) |

### File size reduction

| Asset | Baseline | PR #839 | Loco 3.3 |
| --- | --- | --- | --- |
| Overall payload | 15.2MB | 12.8MB (**15.8%**) | 12.5MB (**17.8%**) |
| `homepageEvents.bundle.js` | 2.2MB | 764KB (**65.3%**) | 822KB (**62.6%**) |
| `main.css` | 722MB | 558KB (**22.7%**) | 211KB (**70.8%**) |
| `vendor.bundle.js` | 567KB | 350KB (**38.3%**) | 350KB (**38.3%**) |
| `experts.bundle.js` | 421KB | 156KB (**63%**) | 155KB (**63.2%**) |
| `spotlights.bundle.js` | 415KB | 153KB (**63.1%**) | 152KB (**63.4%**) |

**Comment by tahirpoduska** [comment]
@cappadona It seems like UglifyJS is pretty chatty. https://github.com/webpack/webpack/issues/2352.
I think we can safely ignore these, and configure uglify to not show the warnings. I looked at a few of these, some are simple issue like setting a variable to true/false when initializing in our code. Some are from external libraries that webpack bundles up.

**Comment by tahirpoduska** [comment]
@cappadona main.css in the browser has additional info about source mapping. There is an option in [cssnano to set it to true to print it inline](http://cssnano.co/options/).

**Comment by cappadona** [comment]
Good catch on the sourcemap for `main.css`. I'm seeing it in [production](http://mannlib.cornell.edu/sites/56e8640e3d262f7310000000/theme/stylesheets/main.css?1479159427), but not dev, which makes me think that cssnano is not the culprit but that something further upstream in the Webpack config is responsible.

**Comment by tahirpoduska** [comment]
Yes, that was my guess as well, probably the css/style loader.

**Comment by cappadona** [comment]
Interesting, looks like [default for `sourceMap` option in css-loader is false](https://github.com/webpack-contrib/css-loader#options-1) and I'm not seeing where we explicitly enabled it in our config.

**Comment by cappadona** [comment]
It might be the [`extract-text-webpack-plugin`](https://github.com/webpack-contrib/extract-text-webpack-plugin/blob/webpack-1/README.md)...need to take a closer look.

**Comment by cappadona** [comment]
You can see that in a previous incarnation of our Webpack config, I had enabled sourcemaps, but they should have been disabled with 43a9402 from July 2016.

Since I'm not currently seeing sourcemaps in the latest on the dev branch, I'm thinking we've finally left this ghost behind, but I'll be curious to hear what you find after rebasing your PR on dev.

> P.S. If you're interested in following that link to the css-loader docs [from my comment](https://github.com/cul-it/mann-wagon/commit/43a9402d16e6b2e43bb6a3ea46c738c3fac8aae4#diff-11e9f7f953edc64ba14b0cc350ae7b9dR50) in the above mentioned commit, you can now find it here:
https://github.com/webpack-contrib/css-loader/blob/68f5a6975a88f6848adde45e6eeb8b000b4ef553/README.md#disable-behavior

**Comment by cappadona** [comment]
Found the [*source*](https://github.com/cul-it/mann-wagon/commit/89067444296857b98a8074447358b04571181940#diff-642224899a7aee531d6c26057b2b1a05R5) of our sourcemaps :)

**Pull request merged**
