### PR TITLE
Per page alerts managed in the back office

### LINKED ISSUE #1046: Add alert to top of all space finder pages

### LINKED ISSUE #1058: Dynamic alerts managed in back office
Power to the content contributors!

### PR DESCRIPTION
**Pull request by cappadona**
Deployed to dev with an example on the [space finder](http://mannlib-dev.internal.library.cornell.edu/locomotive/thoughtless-marsh-6015/preview/use/spaces/)

> Resolves #1058

### CODE REVIEW

**Review by eeh53 — COMMENTED** [review]
I think the opacity is effective - hopefully it passes accessibility! I think this is good to go from my perspective as long as we adjust the text in the alert box to say "1st and 2nd floors" for the quiet study space.

**Comment by cappadona** [comment]
Thanks @eeh53. I think [your review](https://github.com/cul-it/mann-wagon/pull/1064#pullrequestreview-476686256) above was intended for #1063, correct?

**Comment by eeh53** [comment]
@cappadona Yes? I think I got confused, haha. So this is actually looking in the back-end to see how the alerts can be edited?

**Review by sew268 — COMMENTED** [review]
also looks good to me

**Comment by cappadona** [comment]
Merged but not yet deployed to production. @sew268 @eeh53 – Do I have the 🟢 ?

**Comment by cappadona** [comment]
Deployed to production!

**Pull request merged**
